【作業中】Support 2d image source
utrad-ical/circus pull request #194
Opened 2021-09-29 11:09 UTC by doramari

【作業中】2D モードの ImageSource の作成
https://circus-design-note.netlify.app/log/202107-2d-image-source.html

2021-11-08 01:46 UTC, doramari commented on packages/circus-rs/src/browser/image-source/cache/cache-util.ts
> +// HACK: Support-2d-image-source
キャッシュの作成方法 および 関数の名称・配置について確認ください。

2021-11-08 01:48 UTC, doramari commented on packages/circus-rs/src/browser/image-source/drawToImageData.ts
> +// HACK: Support-2d-image-source
モノクロ画像の作成方法（ウィンドウ処理を含む） および 関数の名称・配置について確認ください。

2021-11-08 01:49 UTC, doramari commented on packages/circus-rs/src/browser/section-util.ts
> +// HACK: Support-2d-image-source
関数の名称・配置について確認ください。

2021-11-08 01:51 UTC, doramari commented on packages/circus-rs/src/browser/image-source/cache/cache-util.ts
> +export const createCanvasImageSource = (
キャッシュの作成方法 および 関数の名称・配置について確認ください。

2021-11-08 01:52 UTC, doramari commented on packages/circus-rs/src/browser/image-source/cache/cache-util.ts
> +// HACK: Support-2d-image-source
キャッシュの作成方法 および 関数の名称・配置について確認ください。

2021-11-08 02:07 UTC, doramari commented on packages/circus-rs/src/browser/section-util.ts
> +// HACK: Support-2d-image-source
関数の名称・配置について確認ください。

2021-11-08 02:08 UTC, doramari commented on packages/circus-rs/src/browser/tool/state/handleMoveBy.ts
> +// HACK: Support-2d-image-source
ハンドツールの2Dイメージ対応について確認ください。

2021-11-08 02:09 UTC, doramari commented on packages/circus-rs/src/browser/tool/state/handlePageBy.ts
> +// HACK: Support-2d-image-source
ページツールの2Dイメージ対応について確認ください。

2021-11-08 02:09 UTC, doramari commented on packages/circus-rs/src/browser/tool/state/handlePageBy.ts
> +// HACK: Support-2d-image-source
スクロールバーの2Dイメージ対応について確認ください。

2021-11-08 02:09 UTC, doramari commented on packages/circus-rs/src/browser/tool/state/handleZoomBy.ts
> +// HACK: Support-2d-image-source
ズームツールの2Dイメージ対応について確認ください。

2021-11-08 02:10 UTC, doramari commented on packages/circus-rs/src/server/helper/createVolumeProvider.ts
> +// HACK: Support-2d-image-source
3D画像っぽいかどうか判定している関数です。実装についてご確認ください。

2021-11-08 02:13 UTC, doramari commented on packages/circus-web-ui/src/pages/case-detail/LabelSelector.tsx
> +    // HACK: Support-2d-image-source
2Dイメージ対応のため、ViewerMode を用意し、newViewerCellItem 関数の引数に追加しましたが、よろしかったでしょうか？

2021-11-08 02:13 UTC, doramari commented on packages/circus-web-ui/src/pages/case-detail/ViewerGrid.tsx
> +// HACK: Support-2d-image-source
2Dイメージ対応のため、ViewerMode を用意し、newViewerCellItem 関数の引数に追加しましたが、よろしかったでしょうか？

2021-11-08 02:13 UTC, doramari commented on packages/circus-web-ui/src/pages/case-detail/caseStore.ts
> +// HACK: Support-2d-image-source
2Dイメージ対応のため、ViewerMode を用意し、newViewerCellItem 関数の引数に追加しましたが、よろしかったでしょうか？

2021-11-11 10:08 UTC, smikitky requested changes

2021-11-11 10:08 UTC, smikitky commented on packages/circus-web-ui/src/pages/case-detail/ViewerGrid.tsx
> +// HACK: Support-2d-image-source
はい。

2021-11-12 00:02 UTC, smikitky commented on packages/circus-rs/src/browser/image-source/cache/cache-util.ts
> +// HACK: Support-2d-image-source
万一 ImageData がキャッシュできない場合は代わりに { width, height, arrayBuffer } のようなオブジェクトをキャッシュしてください

2021-11-12 00:43 UTC, doramari commented on packages/circus-rs/src/browser/tool/state/handleMoveBy.ts
> +// HACK: Support-2d-image-source
言葉が足りずにすみません。ツール対応のためにここを修正しましたいうことをお伝えしたかっただけになります。

2021-11-12 01:47 UTC, genkn commented on packages/circus-rs/src/browser/image-source/cache/cache-util.ts
> +// HACK: Support-2d-image-source
最終的に欲しい2d画像を得るためには
(1) バックキャンバスに対して、**指定の位置、大きさで**【画像 = CanvasImageSource】を描画
(2) バックキャンバスの描画内容を `ImageData` として返す
という流れになります。

バックキャンバスへ描画する際、ズームや手のひらツールを反映するためには `drawImage()` を使用しています。
この `drawImage()` が受け付ける image は `CanvasImageSource` である必要があります。
`ImageData` を `CanvasImageSource` にするためには、明らかにコストが高そうな `dataURL()` による変換が必要であるようです。

`ImageData` をキャッシュできないわけではないのですが、描画毎に `dataURL()` を呼ばれるくらいなら ... と思って、`ImageBitmap` をキャッシュしたほうが良いと伝えました。

2021-11-18 08:44 UTC, doramari commented on packages/circus-rs/src/browser/section-util.ts
> +// HACK: Support-2d-image-source
sectionTo2dViewState  に修正しました。

2021-11-18 08:44 UTC, doramari commented on packages/circus-rs/src/browser/section-util.ts
> +// HACK: Support-2d-image-source
sectionFrom2dViewState に修正しました。

2021-11-18 08:50 UTC, doramari commented on packages/circus-lib/src/image-extractor/dicomImageExtractor.test.ts
> +      }
申し訳ございません、そもそも Uint32Array を使用する必要がありませんでした。
修正いたしましたので dicomImageExtractor.ts をご確認ください。

2021-11-18 08:52 UTC, doramari commented on packages/circus-rs/src/browser/annotation/Ruler.ts
> +    })();
共通の関数にまとめました。packages/circus-rs/src/browser/annotation/helper/determineColor.ts をご確認ください。

2021-11-18 08:52 UTC, doramari commented on packages/circus-lib/src/image-extractor/dicomImageExtractor.ts
> +      : ((red << 24) + (green << 16) + (blue << 8) + alpha) >>> 0;
申し訳ございません、そもそも Uint32Array を使用する必要がありませんでした。
修正いたしましたので dicomImageExtractor.ts をご確認ください。

2021-11-18 08:53 UTC, doramari commented on packages/circus-rs/src/common/RawData.ts
> +    // NOTE: In the case of color image (rgba8), returns incorrect value.
protected applyWindow(width: number, level: number, pixel: number): number を削除しました。ご確認ください。

2021-11-18 08:54 UTC, doramari commented on packages/circus-rs/src/browser/image-source/drawToImageData.ts
> +        applyWindow(window.width, window.level, buffer[srcIdx])
不要な Math.round を除去しました。

2021-11-18 08:56 UTC, doramari commented on packages/circus-web-ui/src/components/ImageViewer.tsx
> +export const setOrthogonal2D = (
getInitial2dViewState に修正しました。ご確認ください。

2021-11-18 08:57 UTC, doramari commented on packages/circus-rs/src/browser/image-source/TwoDimensionalImageSource.ts
> +    let key: string = 'imageNumber:' + imageNumber + ';';
ご指摘いただいた通りに修正しました。

2021-11-18 09:01 UTC, doramari commented on packages/circus-rs/src/browser/image-source/drawToImageData.ts
> +  buffer: Uint8Array | Uint8ClampedArray | Uint16Array,
一般的な typed array に型を変更しました。一般的な型が typescript にそもそも存在しないため、three で定義されている TypedArray  を利用しています。自前で定義したほうがよろしければその旨お知らせください。
`type TypedArray = Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | Uint16Array | Int32Array | Uint32Array | Float32Array | Float64Array;
`

2021-11-18 09:02 UTC, doramari commented on packages/circus-rs/src/browser/image-source/drawToImageData.ts
> +  imageData.data.set(buffer8);
大変申し訳ございません。修正しました。ご確認ください。

2021-11-18 09:03 UTC, doramari commented on packages/circus-rs/src/browser/image-source/drawToImageData.ts
> +  viewer: Viewer,
ご指摘ありがとうございます。修正いたしました。

2021-11-18 09:03 UTC, doramari commented on packages/circus-rs/src/browser/section-util.ts
> +    xAxis: [...xAxis, 0],
スプレッドを使用しないよう修正しました。

2021-11-18 09:08 UTC, doramari commented on packages/circus-rs/src/server/helper/createVolumeProvider.ts
> +// HACK: Support-2d-image-source
関数名を再考し、実装についても見直しました。createVolumeProvider.ts をご確認ください。

2021-11-18 09:11 UTC, doramari commented on packages/circus-lib/src/image-extractor/dicomImageExtractor.ts
> +  if (!/^MONOCHROME/.test(photometricInterpretation)) {
修正しました。ご確認ください。

2021-11-22 05:58 UTC, smikitky commented on packages/circus-rs/src/browser/image-source/cache/cache-util.ts
> +// HACK: Support-2d-image-source
以下の API を使うと ImageData から ImageBitmap へと、data URL も裏キャンバスみたいなものも使わず低コストに変換できるみたいです。

https://developer.mozilla.org/ja/docs/Web/API/createImageBitmap

以下で試してみましたが問題なさそうです。

https://codepen.io/smikitky/pen/YzxMjaX

拡大やパンのたびに毎フレームこれを使ってもコストは低いと思いますが、確かに ImageData そのものよりは上記の方法で ImageBitmap までしてからそちらをキャッシュするほうが良さそうですね。

2021-11-22 06:44 UTC, smikitky commented on packages/circus-rs/src/browser/image-source/cache/cache-util.ts
> +// HACK: Support-2d-image-source
繰り返しですが、何にせよ `CanvasImageSource` は意味が広すぎる上に名前が非常に紛らわしいので、`ImageBitmap` 決め打ちでキャッシュにしてください。

2021-11-26 02:36 UTC, closed without merging