Make "Go to next/previous case/job" buttons
utrad-ical/circus pull request #195
Opened 2021-10-04 08:19 UTC by ttakenaga

2021-10-15 04:48 UTC, ttakenaga commented
CIRCUS DBにて編集中にページを移動・更新・閉じるときalertにて警告を追加。

問題点
- Logoutクリック時、警告は出るがすり抜ける。
- voxelラベルは前回保存時との比較が不十分。`voxelShrinkToMinimum()`によるsize・originの変更をラベルの更新と誤判定中。

2021-11-15 04:01 UTC, smikitky requested changes
現在は無条件で「検索」画面の中身を参照しているようですが、マイリストから caseDetail / jobDetail を開いた場合、それぞれそのマイリストの中で移動できるようにしてください。

前どこかで言った気がしますが、検索画面から詳細画面に飛ぶボタンのところで `NextPreviousButton` に渡すための `list` を保存するような操作をするほうがいいのではと思います。

2021-11-15 04:01 UTC, smikitky commented on packages/circus-web-ui/src/pages/MainNav.tsx
> +    'results' in searchedCaseResult;
- `disp` ではなく `show` を使ってください（disp のような省略語は英語的に良くない気がするので）
- `Object(searchedCaseResult) === searchedCaseResult` という条件はちょっとよく分かりません…。optional chaining を使い、うしろ2つは、`searchedCaseResult?.results` でいいのでは。

2021-11-15 06:30 UTC, smikitky commented on packages/circus-web-ui/src/pages/case-detail/CaseDetail.tsx
> +  }, []);
DOMにイベントハンドラを登録する時に `element.onなんちゃら = 関数` という形式を使うのは基本やめてください。元のコードだと、コードのほかの部分で window にイベントハンドラを登録しているコードがあると、それと競合してしまいます（まあめったにないとは思いますが）。以下のようなコードの方が望ましいです。

```suggestion
  useEffect(() => {
    if (isUpdated) {
      const handler = () => true;
      window.addEventListener('beforeunload', handler);
      return () => window.removeEventListener('beforeunload', handler);
    }
  }, [isUpdated]);
```

2021-11-17 04:14 UTC, ttakenaga commented on packages/circus-web-ui/src/pages/case-detail/CaseDetail.tsx
> +  }, []);
`window.onbeforeunload`に直接代入していた個所を `window.addEventListener() `と `beforeunload` イベントを使用して書き直すと、編集時に”再読み込み・タブ閉じ・閉じる”際にアラートが表示されないため、一旦[こちらの修正](https://github.com/utrad-ical/circus/pull/195#discussion_r748987554)で直したものをpushしています。

2021-11-17 05:30 UTC, smikitky commented on packages/circus-web-ui/src/pages/case-detail/CaseDetail.tsx
> +  }, []);
多分 `ev.preventDefault()` してないから？

https://stackoverflow.com/a/25763325/1209240

2021-11-17 05:52 UTC, ttakenaga commented on packages/circus-web-ui/src/pages/case-detail/CaseDetail.tsx
> +  }, []);
ありがとうございます！代入していた関数を`BeforeUnloadEvent.returnValue`につっこむことで動作するようになりました。レビューお願いします。

2021-11-25 05:40 UTC, smikitky approved these changes

2021-11-25 05:40 UTC, merged