Support 2d image source
utrad-ical/circus pull request #207
Opened 2021-11-26 02:38 UTC by doramari

2D モードの ImageSource の作成
https://circus-design-note.netlify.app/log/202107-2d-image-source.html

2021-11-29 05:01 UTC, smikitky commented
胸部単純写真などでのウィンドウ処理が想定外に遅かったので d506396 でウィンドウ処理を少しでも高速化する処理を入れました。

- ImageData のインスタンスに直接書き込むことでメモリコピーを削減
- ウィンドウ処理の四則演算を少しでも削減
- Math.round や 0-255 範囲外の処理をスキップ（どうせ Uint8ClumpedArray が[同じ処理をする](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray)ので）

2021-11-29 06:35 UTC, smikitky requested changes
- プライマリシリーズが 2D なケースを開くと、layout がとりあえず空っぽの 2x2 で始まって、メタデータを呼んだ後に 1x1 にリセットされている感じの挙動をしていますが、見た目がよくないので、metadata の呼び出しが終わってから ViewerCluster を呼び出すように変更をお願いします。
- ラベルセレクタ下部にある "Add series" でシリーズを追加/削除した場合の動作が不安定です。恐らく 3D モードと 2D モードが混在している時に起きている気がします。`SeriesInfo` コンポーネントがエラーを出しており、直接的な原因は metadata が正しく渡っていないのが理由のようです。

2021-11-29 06:35 UTC, smikitky commented on packages/circus-web-ui/src/pages/case-detail/RevisionEditor.tsx
> +  }, [series]);
これは何のために存在しているのでしょうか。

ラベルセレクタの下部にある "Add Series" ボタンでシリーズを追加した場合、恐らくここで既存のデータがリセットされてしまうためにエラーが起きています。

2021-11-29 06:39 UTC, smikitky commented
カラー画像でウィンドウツールを使おうとすると、"You cannot change the window of color images" のようなダイアログが無限に出てきて操作不能になります。こちらも修正をお願いします。

2021-11-30 05:10 UTC, doramari commented
> * カラー画像でウィンドウツールを使おうとすると、"You cannot change the window of color images" のようなダイアログが無限に出てきて操作不能になってしまいます。

alert を表示しないように修正します。

2021-11-30 05:45 UTC, doramari commented
> * カラー画像でウィンドウツールを使おうとすると、"You cannot change the window of color images" のようなダイアログが無限に出てきて操作不能になってしまいます。

alert は dragHandler ではなく dragStartHandler で表示させるよう修正しました。

2021-12-02 03:24 UTC, doramari commented
> * プライマリシリーズが 2D なケースを開くと、layout がとりあえず空っぽの 2x2 で始まって、メタデータを呼んだ後に 1x1 にリセットされている感じの挙動をしていますが、見た目がよくないので、metadata の呼び出しが終わってから ViewerCluster を呼び出すように変更をお願いします。

アクティブシリーズのメタデータのロードが済んでから、ViewerGrid を描画するように修正しました。

2021-12-02 03:24 UTC, doramari commented
> * ラベルセレクタ下部にある "Add series" でシリーズを追加/削除した場合の動作が不安定です。恐らく 3D モードと 2D モードが混在している時に起きている気がします。`SeriesInfo` コンポーネントがエラーを出しており、直接的な原因は metadata が正しく渡っていないのが理由のようです。

master ブランチですでに発現しているエラーのようです。一度 master ブランチで "Add series" でシリーズを追加し、不安定だと感じた動作についてご確認いただけませんでしょうか？

2021-12-02 03:25 UTC, doramari commented on packages/circus-rs/src/browser/image-source/drawToImageData.ts
> +): ImageData {
drawToImageData という既存の関数を拡張したものとして同じ関数にまとめました。ご確認ください。

2021-12-02 03:26 UTC, doramari commented on packages/circus-rs/src/browser/annotation/helper/determineColor.ts
> +const determineColor = (
ご指摘いただいた関数は以前に同じような判定が複数個所にあるので集約をというご指示を頂き作成した関数でしたが、今回のご指摘と合わせて加納に相談したところ、無理に集約するのはやめたほうが良いという結果になりました。各アノテーションで判定をするように戻し、コードを再度見直した上で push いたしましたのでご確認ください。

-  判断の基準となる distance に該当する値の取得方法がアノテーションごとに異なる。
-  判断の基準となる アノテーションのプロパティ値 の名称も、アノテーションによって異なる。
-  アノテーションによっては、線だけではなく、塗りつぶし色 の判定も必要。
-  (1) つまり無理に1つの関数にしようとすると、大量の引数が必要になり、しかも場合によっては引数にundefinedを渡したりといったコードになりそうです。
-  (2) 別の方針としては抽象クラスを間に挟み、しかもその抽象クラスは子クラスに対して判定に使用する値を返すための protected な getter の定義を強制する形となります。
-  (1),(2)ともに残念なので、現時点では概念としてシンプルになる (state: ViewState) => 必要な色 を各箇所で定義する形が一番マシだと判断しました。

2021-12-13 06:52 UTC, smikitky approved these changes

2021-12-13 06:52 UTC, merged