Use a websocket connection to transfer each image of volume data.
utrad-ical/circus pull request #261
Opened 2022-04-18 04:59 UTC by genkn

2022-08-08 07:04 UTC, smikitky requested changes
- `circus-rs/src/demo` にあるデモ目的でしか使われていないコードについて `circus-rs/demo` に移動をお願いします。
- Prettier がかかり忘れていると思われる部分が散見されるので確認をお願いします。
- console.log はいずれ削除してください。

2022-08-08 07:04 UTC, smikitky commented on packages/circus-rs/src/server/ws/createWebsocketVolumeRoute.ts
> +export type RsWebsocketVolumeRoute = (option: { authFunctionProvider: AuthFunctionProvider; }) => WebSocketConnectionHandler;
「Handler を作るための関数を Route と呼ぶ」というのは直感的ではない気がします。

`WebSocketRequestHandlerFactory` とか？

2022-08-19 08:29 UTC, genkn commented on packages/circus-rs/src/common/ws/message.ts
> +const endOfJson = 0x0a;
```ts
const messageView = new Uint8Array(messageBuffer);
const endOfJsonIndex = messageView.indexOf(endOfJson);
```
このパターンで endOfJson が2文字となると、先に文字列にデコードする必要が出てきます。後日相談させてください。

2022-08-22 01:40 UTC, genkn commented on packages/circus-rs/src/common/ws/message.ts
> +export type MessageDataType = typeof MessageDataType[keyof typeof MessageDataType];
修正済みです。

2022-08-22 01:41 UTC, genkn commented on packages/circus-rs/src/browser/ws/WebSocketClient.ts
> +interface IWebSocketClient {
修正しました。

2022-08-22 01:41 UTC, genkn commented on packages/circus-rs/src/browser/ws/createTransferConnectionFactory.ts
> +};
修正しました。

2022-08-22 01:42 UTC, genkn commented on packages/circus-rs/src/browser/ws/createTransferConnectionFactory.ts
> +export type TransferConnection = {
修正しました。

2022-08-22 01:42 UTC, genkn commented on packages/circus-rs/src/browser/ws/createTransferConnectionFactory.ts
> +        const stop = () => {
修正しました。

2022-08-22 01:47 UTC, genkn commented on packages/circus-rs/src/browser/ws/createTransferConnectionFactory.ts
> +export interface TransferConnectionFactory {
同感です。修正しました。

2022-08-22 01:47 UTC, genkn commented on packages/circus-rs/src/common/ws/message.ts
> +    messageType: typeof MessageDataType.BEGIN_TRANSFER;
修正しました。

2022-08-22 01:48 UTC, genkn commented on packages/circus-rs/src/server/ws/connection/WebSocketConnectionHandler.ts
> +type WebSocketConnectionHandler = (ws: WebSocket, request: IncomingMessage) => void;
本件について、よりよいネーミングについて相談させてください。
私もここは、最適な名前を付けたいポイントだと考えています。

2022-08-22 01:49 UTC, genkn commented on packages/circus-rs/src/server/ws/createWebsocketVolumeRoute.ts
> +export type RsWebsocketVolumeRoute = (option: { authFunctionProvider: AuthFunctionProvider; }) => WebSocketConnectionHandler;
本件について、よりよいネーミングについて相談させてください。
私もここは、最適な名前を付けたいポイントだと考えています。

2022-08-22 02:10 UTC, genkn commented on packages/circus-rs/src/browser/viewer/Viewer.ts
> +
L: 313 あたり。
```ts
          this.cachedSourceImage = drawResult.draft;
          if (!this.nextRender) {
            drawResult.next().then(drawResult =>
              handleImageDraw(drawnState, drawResult)
            );
          }
```
これは、自動で止まるので問題ないように思えます。相談させてください。

2022-08-22 06:57 UTC, smikitky commented on packages/circus-rs/src/server/ws/connection/WebSocketConnectionHandler.ts
> +type WebSocketConnectionHandler = (ws: WebSocket, request: IncomingMessage) => void;
Handler called when a WebSocket connection is established

2022-08-22 06:58 UTC, genkn commented on packages/circus-rs/src/server/ws/connection/WebSocketConnectionHandler.ts
> +type WebSocketConnectionHandler = (ws: WebSocket, request: IncomingMessage) => void;
コメントを付けて、このままの名前で。

2022-08-22 10:18 UTC, genkn commented on packages/circus-rs/src/browser/util/getRequiredImageZIndexRange.ts
> +export default function getRequiredImageZIndexRange(section: Section, metadata: DicomVolumeMetadata): [number, number] {
お打ち合わせありがとうございました。
ご相談結果を反映済みです。

2022-08-22 10:21 UTC, genkn commented on packages/circus-rs/src/common/ws/message.ts
> +const endOfJson = 0x0a;
ご相談結果の通り、バイト配列で２要素の確認を行う、または、先に文字列化しなくてはならないことが問題（面倒）なので今回はこのままにします。

2022-08-22 10:21 UTC, genkn commented on packages/circus-rs/src/server/ws/createWebsocketVolumeRoute.ts
> +export type RsWebsocketVolumeRoute = (option: { authFunctionProvider: AuthFunctionProvider; }) => WebSocketConnectionHandler;
ご相談結果を反映してあります。

2022-08-22 10:22 UTC, genkn commented on packages/circus-rs/src/browser/viewer/Viewer.ts
> +
本日お打ち合わせ中にございました abortController の扱いの変更を反映済みです。

2022-08-31 17:00 UTC, genkn commented on packages/circus-rs/src/server/createServer.ts
> +    '/ws/hello': hello,
対応しました。

2022-08-31 18:18 UTC, genkn commented
遅くなって申し訳ありません。
テストの fix に苦労しました。

(1) prettier

既存コードもかかっていないところがあります。
比較がより困難になることを防ぐために、こちらではかけていません。
マージ後にそちらで全コード一括、master でお願いできないでしょうか。

(2) ws volume 通信の認可(seriesUid に対する認可)について
    - packages/circus-api/src/createApp.ts
    - packages/circus-rs/src/server/createServer.ts

現在の定義では `authFunctionProvider: req => async seriesUid => true` となっているため、
websocket 接続後は、その接続を使用すると認可なく全ての volume にアクセスできてしまいます。

```ts
// [createAuthFunctionProvider.ts]
type AuthFunction = (seriesUid: string) => Promise<boolean>;
type AuthFunctionProvider = (req: IncomingMessage /*初回のws接続時の要求*/ ) => AuthFunction;
const createAuthFunctionProvider: FunctionService<AuthFunctionProvider, ...> = ...
export default createAuthFunctionProvider;
```

のように定義をして、

`createWebsocketVolumeConnectionHandlerCreator` の依存を調整する方法が良いと思うのですが、
`AuthFunctionProvider` の認可まわりの実装は、皆目見当がつきません。

こちらの実装はお願いできないでしょうか。

また、認可周りの問題として、
Aさんでログイン⇒ ws接続*1 ⇒ Bさんでログイン
としたときに、*1の接続が残っていた場合、Bさんでログインしているにも関わらず、認可関数はAさんの認証のものが使用されてしまうはずです。
ログアウトに伴うページの離脱が発生しない場合、これは大きな問題になりそうです。
ログアウト時に、全ての接続を切るような対応が必要かもしれません。

2022-09-12 08:15 UTC, genkn commented
先ほどはお打ち合わせありがとうございました。
いくつか、打合せの内容から変更して push しました。

1. websocket の切断について
    - `LoginScreen` ではなく `VolumeLoaderFactoryProvider` (`packages/circus-web-ui/src/index.tsx`) に実装しました。
    - （LoginScreen に変更はありません）

2. `setToken` をやめてコンストラクタの引数にしました。

よろしくお願いいたします。

2022-10-16 08:39 UTC, smikitky approved these changes

2022-10-16 08:39 UTC, merged